[workspace]
members = [
    "cliphoard",
    "cliphoard-schema",
    "cliphoard-decode",
    "cliphoard-daemon",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Isa Al-Ula <isaalula@proton.me>"]
license = "MPL-2.0"
repository = "https://github.com/al-ula/cosmic-cliphoard"
