// SPDX-License-Identifier: MPL-2.0

//! D-Bus interface constants and proxy definition for the cliphoard backend service.
//!
//! The backend implements the interface using `#[zbus::interface]` on its own struct.
//! Clients use the proxy generated here to call into the backend.

/// D-Bus proxy for the clipboard manager service.
///
/// Generated by `zbus::proxy` — used by applet, app, and tray to talk to the backend.
/// Entry data is transferred over D-Bus as bincode-encoded bytes for efficiency.
#[zbus::proxy(
    interface = "com.github.al_ula.Cliphoard.Manager",
    default_service = "com.github.al_ula.Cliphoard",
    default_path = "/com/github/al_ula/Cliphoard"
)]
pub trait ClipboardManager {
    /// Get all entries as bincode-encoded bytes.
    fn list_entries(&self) -> zbus::fdo::Result<Vec<u8>>;

    /// Get a single entry by ID as bincode-encoded bytes.
    fn get_entry(&self, id: u64) -> zbus::fdo::Result<Vec<u8>>;

    /// Search entries by text query, returns bincode-encoded Vec<ClipboardEntry>.
    fn search(&self, query: &str) -> zbus::fdo::Result<Vec<u8>>;

    /// Delete an entry by ID. Returns true if found and deleted.
    fn delete_entry(&self, id: u64) -> zbus::fdo::Result<bool>;

    /// Pin an entry to prevent eviction.
    fn pin_entry(&self, id: u64) -> zbus::fdo::Result<bool>;

    /// Unpin an entry.
    fn unpin_entry(&self, id: u64) -> zbus::fdo::Result<bool>;

    /// Clear all non-pinned entries.
    fn clear(&self) -> zbus::fdo::Result<()>;

    /// Paste an entry by ID (writes it to the clipboard via wl-copy).
    fn paste_entry(&self, id: u64) -> zbus::fdo::Result<bool>;

    /// Signal emitted when a new entry is added.
    #[zbus(signal)]
    fn entry_added(&self, id: u64) -> zbus::Result<()>;

    /// Signal emitted when an entry is removed.
    #[zbus(signal)]
    fn entry_removed(&self, id: u64) -> zbus::Result<()>;

    /// Signal emitted when history is cleared.
    #[zbus(signal)]
    fn history_cleared(&self) -> zbus::Result<()>;
}
